### ISSUE TITLE
wrong indentation

### ISSUE THREAD

**Issue by steveklabnik** [Ivo-Balbaert/start_rust#3]
https://github.com/Ivo-Balbaert/start_rust/blob/master/Chapter%202/code/type_errors.rs#L13 is indented differently than the rest of the lines

**Comment by steveklabnik** [comment]
same with https://github.com/Ivo-Balbaert/start_rust/blob/master/Chapter%204/code/arrays.rs#L47

**Comment by steveklabnik** [comment]
https://github.com/Ivo-Balbaert/start_rust/blob/master/Chapter%204/code/input.rs#L6-L8

**Comment by steveklabnik** [comment]
https://github.com/Ivo-Balbaert/start_rust/blob/master/Chapter%204/code/pattern_match.rs#L6-L8

**Comment by steveklabnik** [comment]
I'll just leave it at that, might want to check the rest :)

**Comment by Ivo-Balbaert** [comment]
will do, thanks!

**Comment by steveklabnik** [comment]
:)
